// MIT License Copyright (C) 2022 kubefay@https://github.com/kubefay/kubefay
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	agentv1alpha1 "github.com/kubefay/kubefay/pkg/apis/agent/v1alpha1"
	versioned "github.com/kubefay/kubefay/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kubefay/kubefay/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kubefay/kubefay/pkg/client/listers/agent/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AntreaAgentInfoInformer provides access to a shared informer and lister for
// AntreaAgentInfos.
type AntreaAgentInfoInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AntreaAgentInfoLister
}

type antreaAgentInfoInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewAntreaAgentInfoInformer constructs a new informer for AntreaAgentInfo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAntreaAgentInfoInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAntreaAgentInfoInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredAntreaAgentInfoInformer constructs a new informer for AntreaAgentInfo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAntreaAgentInfoInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgentV1alpha1().AntreaAgentInfos().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgentV1alpha1().AntreaAgentInfos().Watch(context.TODO(), options)
			},
		},
		&agentv1alpha1.AntreaAgentInfo{},
		resyncPeriod,
		indexers,
	)
}

func (f *antreaAgentInfoInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAntreaAgentInfoInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *antreaAgentInfoInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&agentv1alpha1.AntreaAgentInfo{}, f.defaultInformer)
}

func (f *antreaAgentInfoInformer) Lister() v1alpha1.AntreaAgentInfoLister {
	return v1alpha1.NewAntreaAgentInfoLister(f.Informer().GetIndexer())
}
