// MIT License Copyright (C) 2022 TicktW@https://github.com/TicktW/kubefay
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/TicktW/kubefay/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// AntreaAgentInfos returns a AntreaAgentInfoInformer.
	AntreaAgentInfos() AntreaAgentInfoInformer
	// AntreaControllerInfos returns a AntreaControllerInfoInformer.
	AntreaControllerInfos() AntreaControllerInfoInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// AntreaAgentInfos returns a AntreaAgentInfoInformer.
func (v *version) AntreaAgentInfos() AntreaAgentInfoInformer {
	return &antreaAgentInfoInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// AntreaControllerInfos returns a AntreaControllerInfoInformer.
func (v *version) AntreaControllerInfos() AntreaControllerInfoInformer {
	return &antreaControllerInfoInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
