// MIT License Copyright (C) 2022 TicktW@https://github.com/TicktW/kubefay
// Code generated by client-gen. DO NOT EDIT.

// This package contains the scheme of the automatically generated clientset.
package scheme
