// MIT License Copyright (C) 2022 kubefay@https://github.com/kubefay/kubefay
// Code generated by client-gen. DO NOT EDIT.

// This package contains the scheme of the automatically generated clientset.
package scheme
