// MIT License Copyright (C) 2022 TicktW@https://github.com/TicktW/kubefay
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/TicktW/kubefay/pkg/apis/ipam/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSubNets implements SubNetInterface
type FakeSubNets struct {
	Fake *FakeIpamV1alpha1
	ns   string
}

var subnetsResource = schema.GroupVersionResource{Group: "ipam.kubefay.github.com", Version: "v1alpha1", Resource: "subnets"}

var subnetsKind = schema.GroupVersionKind{Group: "ipam.kubefay.github.com", Version: "v1alpha1", Kind: "SubNet"}

// Get takes name of the subNet, and returns the corresponding subNet object, and an error if there is any.
func (c *FakeSubNets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SubNet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(subnetsResource, c.ns, name), &v1alpha1.SubNet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubNet), err
}

// List takes label and field selectors, and returns the list of SubNets that match those selectors.
func (c *FakeSubNets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SubNetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(subnetsResource, subnetsKind, c.ns, opts), &v1alpha1.SubNetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SubNetList{ListMeta: obj.(*v1alpha1.SubNetList).ListMeta}
	for _, item := range obj.(*v1alpha1.SubNetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested subNets.
func (c *FakeSubNets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(subnetsResource, c.ns, opts))

}

// Create takes the representation of a subNet and creates it.  Returns the server's representation of the subNet, and an error, if there is any.
func (c *FakeSubNets) Create(ctx context.Context, subNet *v1alpha1.SubNet, opts v1.CreateOptions) (result *v1alpha1.SubNet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(subnetsResource, c.ns, subNet), &v1alpha1.SubNet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubNet), err
}

// Update takes the representation of a subNet and updates it. Returns the server's representation of the subNet, and an error, if there is any.
func (c *FakeSubNets) Update(ctx context.Context, subNet *v1alpha1.SubNet, opts v1.UpdateOptions) (result *v1alpha1.SubNet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(subnetsResource, c.ns, subNet), &v1alpha1.SubNet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubNet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSubNets) UpdateStatus(ctx context.Context, subNet *v1alpha1.SubNet, opts v1.UpdateOptions) (*v1alpha1.SubNet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(subnetsResource, "status", c.ns, subNet), &v1alpha1.SubNet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubNet), err
}

// Delete takes name of the subNet and deletes it. Returns an error if one occurs.
func (c *FakeSubNets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(subnetsResource, c.ns, name, opts), &v1alpha1.SubNet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSubNets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(subnetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SubNetList{})
	return err
}

// Patch applies the patch and returns the patched subNet.
func (c *FakeSubNets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SubNet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(subnetsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SubNet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubNet), err
}
