apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-worker
  labels:
    app: test-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-worker
  template:
    metadata:
      labels:
        app: test-worker
    spec:
      nodeName: kind-worker
      containers:
      - name: kubefay
        image: kubefay/kubefay-ubuntu:latest
        imagePullPolicy: Never
        command: [ "kubefay-test-server" ]
        ports:
        - containerPort: 80
