apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-master
  labels:
    app: test-master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-master
  template:
    metadata:
      labels:
        app: test-master
    spec:
      nodeName: kind-control-plane         
      containers:
      - name: kubefay
        image: kubefay/kubefay-ubuntu:latest
        imagePullPolicy: Never
        command: [ "/bin/sh","-c","python3 -m http.server" ]
        ports:
        - containerPort: 80
