apiVersion: v1
kind: Pod
metadata:
  name: ipam-static-pod
  labels:
    app: ipam-app
  annotations:
    IPv4: 10.192.255.253
spec:
  nodeName: kind-worker
  containers:
  - name: nginx
    image: projects.registry.vmware.com/antrea/antrea-ubuntu:latest
    imagePullPolicy: Never
    command: [ "/bin/sh","-c","python3 -m http.server" ]
    ports:
    - containerPort: 80
