// MIT License Copyright (C) 2022 kubefay@https://github.com/kubefay/kubefay
// Code generated by client-gen. DO NOT EDIT.

// This package has the automatically generated fake clientset.
package fake
