// MIT License Copyright (C) 2022 TicktW@https://github.com/TicktW/kubefay
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type AntreaAgentInfoExpansion interface{}

type AntreaControllerInfoExpansion interface{}
