// MIT License Copyright (C) 2022 kubefay@https://github.com/kubefay/kubefay
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type AntreaAgentInfoExpansion interface{}

type AntreaControllerInfoExpansion interface{}
