---
apiVersion: ipam.antrea.tanzu.vmware.com/v1alpha1
kind: SubNet
metadata:
  name: newnet
spec:
  # Add fields here
  ipVersion: v4
  cidr: 10.182.0.0/16
  serviceAccountName: antrea-agent
---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-test
  annotations:
    subnet: newnet
