// MIT License Copyright (C) 2022 kubefay@https://github.com/kubefay/kubefay
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// SubNetListerExpansion allows custom methods to be added to
// SubNetLister.
type SubNetListerExpansion interface{}

// SubNetNamespaceListerExpansion allows custom methods to be added to
// SubNetNamespaceLister.
type SubNetNamespaceListerExpansion interface{}
