// MIT License Copyright (C) 2022 TicktW
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "../pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// SubNets returns a SubNetInformer.
	SubNets() SubNetInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// SubNets returns a SubNetInformer.
func (v *version) SubNets() SubNetInformer {
	return &subNetInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
