// MIT License Copyright (C) 2022 kubefay@https://github.com/kubefay/kubefay
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubefay/kubefay/pkg/apis/agent/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AntreaControllerInfoLister helps list AntreaControllerInfos.
// All objects returned here must be treated as read-only.
type AntreaControllerInfoLister interface {
	// List lists all AntreaControllerInfos in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.AntreaControllerInfo, err error)
	// Get retrieves the AntreaControllerInfo from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.AntreaControllerInfo, error)
	AntreaControllerInfoListerExpansion
}

// antreaControllerInfoLister implements the AntreaControllerInfoLister interface.
type antreaControllerInfoLister struct {
	indexer cache.Indexer
}

// NewAntreaControllerInfoLister returns a new AntreaControllerInfoLister.
func NewAntreaControllerInfoLister(indexer cache.Indexer) AntreaControllerInfoLister {
	return &antreaControllerInfoLister{indexer: indexer}
}

// List lists all AntreaControllerInfos in the indexer.
func (s *antreaControllerInfoLister) List(selector labels.Selector) (ret []*v1alpha1.AntreaControllerInfo, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AntreaControllerInfo))
	})
	return ret, err
}

// Get retrieves the AntreaControllerInfo from the index for a given name.
func (s *antreaControllerInfoLister) Get(name string) (*v1alpha1.AntreaControllerInfo, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("antreacontrollerinfo"), name)
	}
	return obj.(*v1alpha1.AntreaControllerInfo), nil
}
