// MIT License Copyright (C) 2022 TicktW@https://github.com/TicktW/kubefay
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AntreaAgentInfoListerExpansion allows custom methods to be added to
// AntreaAgentInfoLister.
type AntreaAgentInfoListerExpansion interface{}

// AntreaControllerInfoListerExpansion allows custom methods to be added to
// AntreaControllerInfoLister.
type AntreaControllerInfoListerExpansion interface{}
